baseURL = "https://AishwaryaRamaswami.github.io/mlnotes/"
languageCode = "en-us"
title = "Aishwarya"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
